### ISSUE TITLE
mmlab version vs. RMLio version

### ISSUE THREAD

**Issue by ktk** [mmlab/RMLProcessor#15]
If I'm not wrong https://github.com/RMLio/RML-Processor is the successor of this repository. If so I propose to close this one here and move the still open issues there. It's really confusing, I thought there was no development for a long time. Looks like quite some of my issues are at least addressed in there.

**Comment by andimou** [comment]
Indeed, you are right that it's confusing but there are references to this repository, so best would be to add an indication to the new repository.
